from . import product_template
from . import purchase_order
from . import purchase_order_line
from . import purchase_request
from . import purchase_request_allocation
from . import purchase_request_line
from . import res_users
from . import stock_location
from . import stock_move
from . import stock_move_line
from . import stock_rule
from . import stock_warehouse_orderpoint
