# -*- coding: utf-8 -*-

{
    'name': 'Affinity Invoice Integration',
    'author': 'Affinity Business Suite',
    'website': 'https://affinitysuite.net',
    'support': 'info@affinitysuite.net',
    'category': 'Accounting',
    'summary': 'Affinity Invoice Integration Module',
    'description': '''Affinity Invoice Integration Module''',
    'version': '18.0',
    'depends': ['account_asset'],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/ir_sequence.xml',
        'wizard/voucher_fetch_wizard_views.xml',
        'views/account_account_views.xml',
        'views/api_fetch_log_views.xml',
    ],
    'assets': {},
    'images': [],
    'price': 4000000,
    'currency': 'EUR',
    'license': 'OPL-1',
    'application': False,
    'auto_install': False,
    'installable': True,
}
