# -*- coding: utf-8 -*-

{
    'name': 'Purchase Request Management',
    'author': 'Affinity Business Suite',
    'website': 'https://affinitysuite.net',
    'support': 'info@affinitysuite.net',
    'category': 'Purchase',
    'summary': 'Purchase Request Management Module',
    'description': '''Purchase Request Management Module''',
    'version': '18.0',
    'depends': ['purchase_stock'],
    'data': [
        'security/ir_module_category.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/ir_sequence.xml',
        'data/mail_message_subtype.xml',
        'report/report_purchase_request_template.xml',
        'report/ir_actions_report.xml',
        'wizard/purchase_request_line_make_purchase_order_views.xml',
        'views/product_template_views.xml',
        'views/purchase_order_line_views.xml',
        'views/purchase_order_views.xml',
        'views/purchase_request_allocation_views.xml',
        'views/purchase_request_views.xml',
        'views/purchase_request_line_views.xml',
        'views/stock_location_views.xml',
        'views/stock_move_views.xml',
        'views/res_users_views.xml',
    ],
    'assets': {},
    'price': 4000000,
    'currency': 'EUR',
    'license': 'OPL-1',
    'application': True,
    'auto_install': False,
    'installable': True,
}
